import type { SectorData, SectorKey } from './types';

const TREND = {
  healthcare: 'M0 40 Q25 38,40 35 T80 32 T110 28 T140 30 T160 22 T180 18 T200 15',
  food: 'M0 38 Q30 36,50 34 T90 30 T130 26 T160 24 T180 20 T200 18',
  financial: 'M0 42 Q20 40,45 36 T85 32 T120 28 T150 26 T175 20 T200 16',
  legal: 'M0 40 Q24 38,50 34 T90 30 T125 27 T155 24 T178 20 T200 17',
  education: 'M0 39 Q28 37,52 33 T92 29 T128 26 T158 23 T180 19 T200 16',
  corporate: 'M0 41 Q22 39,48 35 T88 31 T125 27 T155 25 T178 19 T200 17',
};

export const INITIAL_SECTOR_DATA: Record<SectorKey, SectorData> = {
  healthcare: {
    organisation: 'Healthcare Organisation',
    sectorLabel: 'Healthcare',
    teamTerm: 'Ward',
    metrics: { teams: 24, packsReady: 7, elevated: 3, privacyGate: '✓' },
    trendPath: TREND.healthcare,
    teams: [
      { id: 'h1', name: 'Ward 4A · Medical', state: 'Normal', participation: 92, privacyGate: 'Passed', latestAction: 'Routine review logged', packReadiness: 'Ready' },
      { id: 'h2', name: 'Ward 6B · Surgical', state: 'Normal', participation: 88, privacyGate: 'Passed', latestAction: 'Staffing rebalance complete', packReadiness: 'Ready' },
      { id: 'h3', name: 'ED · Resus', state: 'Watch', participation: 76, privacyGate: 'Passed', latestAction: 'Shift review in progress', packReadiness: 'Draft' },
      { id: 'h4', name: 'ICU · Critical', state: 'Elevated', participation: 71, privacyGate: 'Passed', latestAction: 'Capacity review active', packReadiness: 'Draft' },
    ],
    packs: [
      { id: 'hp1', title: 'Ward 6B Q2 evidence pack', team: 'Ward 6B · Surgical', sector: 'Healthcare', dateRange: 'Apr 1 to Jun 30', readiness: 'Ready' },
      { id: 'hp2', title: 'ICU operating conditions pack', team: 'ICU · Critical', sector: 'Healthcare', dateRange: 'May 1 to Jun 30', readiness: 'Draft' },
      { id: 'hp3', title: 'ED resus review pack', team: 'ED · Resus', sector: 'Healthcare', dateRange: 'Jun 1 to Jun 30', readiness: 'Ready' },
    ],
    interventions: [
      { id: 'hi1', title: 'Staffing rebalance · Ward 6B', team: 'Ward 6B · Surgical', trigger: 'Watch operating conditions', action: 'Staffing rebalance logged', owner: 'Operations Lead', status: 'Resolved', outcome: 'Pressure reducing', followUpDate: '2026-06-12', linkedPack: 'Ward 6B Q2 evidence pack' },
      { id: 'hi2', title: 'Shift review · ED Resus', team: 'ED · Resus', trigger: 'Watch threshold passed', action: 'Shift pattern review opened', owner: 'Clinical Manager', status: 'Active', outcome: 'Under review', followUpDate: '2026-06-10', linkedPack: 'ED resus review pack' },
      { id: 'hi3', title: 'Capacity review · ICU', team: 'ICU · Critical', trigger: 'Elevated operating conditions', action: 'Capacity review logged', owner: 'Organisation Admin', status: 'Active', outcome: 'Action in progress', followUpDate: '2026-06-08', linkedPack: 'ICU operating conditions pack' },
    ],
    auditEvents: [
      { id: 'ha1', type: 'Privacy gate passed', timestamp: '2026-06-06 09:14', actor: 'Organisation Admin', detail: 'Ward 4A · Medical threshold validated for reporting window.' },
      { id: 'ha2', type: 'Operating condition changed', timestamp: '2026-06-05 16:42', actor: 'Manager', detail: 'ICU · Critical moved from Watch to Elevated.' },
      { id: 'ha3', type: 'Management action logged', timestamp: '2026-06-05 11:20', actor: 'Operations Lead', detail: 'Staffing rebalance recorded for Ward 6B · Surgical.' },
      { id: 'ha4', type: 'Evidence pack compiled', timestamp: '2026-06-04 14:05', actor: 'Auditor', detail: 'Ward 6B Q2 evidence pack marked ready for review.' },
      { id: 'ha5', type: 'Pack reviewed', timestamp: '2026-06-03 10:30', actor: 'Organisation Admin', detail: 'ED resus review pack review status updated.' },
    ],
    privacyLog: [
      { id: 'hpl1', team: 'Ward 4A · Medical', check: 'Team size threshold', teamSize: 14, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Team totals only. No individual data stored.' },
      { id: 'hpl2', team: 'Ward 6B · Surgical', check: 'Privacy gate', teamSize: 12, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Threshold passed. Reporting enabled.' },
      { id: 'hpl3', team: 'Micro Team Alpha', check: 'Suppressed period', teamSize: 7, threshold: 10, badge: 'Suppressed', period: 'Week 22', message: 'Below minimum team size. Aggregates withheld.' },
      { id: 'hpl4', team: 'Archive Ward', check: 'Retention purge', teamSize: 11, threshold: 10, badge: 'Purged', period: 'Week 18', message: 'Expired records purged per retention policy.' },
    ],
    policy: {
      minTeamThreshold: 10,
      reviewPeriodWeeks: 4,
      evidenceRetentionMonths: 24,
      watchThreshold: 2.5,
      elevatedThreshold: 3.5,
      sectorLabel: 'Clinical team',
      complianceLabel: 'CQC-ready evidence',
    },
  },
  food: {
    organisation: 'Food Manufacturing Organisation',
    sectorLabel: 'Food',
    teamTerm: 'Production line',
    metrics: { teams: 18, packsReady: 5, elevated: 2, privacyGate: '✓' },
    trendPath: TREND.food,
    teams: [
      { id: 'f1', name: 'Line One · Production', state: 'Normal', participation: 94, privacyGate: 'Passed', latestAction: 'Line audit complete', packReadiness: 'Ready' },
      { id: 'f2', name: 'Packing Team', state: 'Normal', participation: 90, privacyGate: 'Passed', latestAction: 'Throughput review logged', packReadiness: 'Ready' },
      { id: 'f3', name: 'Night Shift Team', state: 'Watch', participation: 78, privacyGate: 'Passed', latestAction: 'Shift handover review', packReadiness: 'Draft' },
      { id: 'f4', name: 'Quality Team', state: 'Elevated', participation: 73, privacyGate: 'Passed', latestAction: 'Corrective action opened', packReadiness: 'Draft' },
    ],
    packs: [
      { id: 'fp1', title: 'Line One hygiene evidence pack', team: 'Line One · Production', sector: 'Food', dateRange: 'Apr 1 to Jun 30', readiness: 'Ready' },
      { id: 'fp2', title: 'QC escalation pack', team: 'Quality Team', sector: 'Food', dateRange: 'Jun 1 to Jun 30', readiness: 'Draft' },
      { id: 'fp3', title: 'Night shift operating pack', team: 'Night Shift Team', sector: 'Food', dateRange: 'May 15 to Jun 30', readiness: 'Ready' },
    ],
    interventions: [
      { id: 'fi1', title: 'Throughput review · Packing', team: 'Packing Team', trigger: 'Watch operating conditions', action: 'Throughput review logged', owner: 'Production Manager', status: 'Resolved', outcome: 'Flow stabilised', followUpDate: '2026-06-11', linkedPack: 'Line One hygiene evidence pack' },
      { id: 'fi2', title: 'Handover review · Night Shift', team: 'Night Shift Team', trigger: 'Watch threshold passed', action: 'Handover checklist updated', owner: 'Shift Supervisor', status: 'Active', outcome: 'Monitoring', followUpDate: '2026-06-09' },
      { id: 'fi3', title: 'Corrective action · QC', team: 'Quality Team', trigger: 'Elevated operating conditions', action: 'Corrective action plan logged', owner: 'Quality Lead', status: 'Active', outcome: 'In progress', followUpDate: '2026-06-07', linkedPack: 'QC escalation pack' },
    ],
    auditEvents: [
      { id: 'fa1', type: 'Privacy gate passed', timestamp: '2026-06-06 08:50', actor: 'Organisation Admin', detail: 'Line One · Production threshold validated.' },
      { id: 'fa2', type: 'Operating condition changed', timestamp: '2026-06-05 15:10', actor: 'Production Manager', detail: 'Quality Control moved to Elevated.' },
      { id: 'fa3', type: 'Management action logged', timestamp: '2026-06-05 09:45', actor: 'Shift Supervisor', detail: 'Night shift handover review recorded.' },
      { id: 'fa4', type: 'Evidence pack compiled', timestamp: '2026-06-04 13:20', actor: 'Auditor', detail: 'Line One hygiene evidence pack compiled.' },
      { id: 'fa5', type: 'Pack reviewed', timestamp: '2026-06-02 11:00', actor: 'Quality Lead', detail: 'Night shift operating pack marked reviewed.' },
    ],
    privacyLog: [
      { id: 'fpl1', team: 'Line One · Production', check: 'Team size threshold', teamSize: 16, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Shift team totals only. No individual data stored.' },
      { id: 'fpl2', team: 'Packing Team', check: 'Privacy gate', teamSize: 13, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Threshold passed. Reporting enabled.' },
      { id: 'fpl3', team: 'Micro Cell B', check: 'Suppressed period', teamSize: 8, threshold: 10, badge: 'Suppressed', period: 'Week 22', message: 'Below minimum team size. Aggregates withheld.' },
      { id: 'fpl4', team: 'Legacy Line', check: 'Retention purge', teamSize: 12, threshold: 10, badge: 'Purged', period: 'Week 17', message: 'Expired records purged per retention policy.' },
    ],
    policy: {
      minTeamThreshold: 10,
      reviewPeriodWeeks: 4,
      evidenceRetentionMonths: 24,
      watchThreshold: 2.4,
      elevatedThreshold: 3.4,
      sectorLabel: 'Shift team',
      complianceLabel: 'BRCGS-ready evidence',
    },
  },
  financial: {
    organisation: 'Financial Services Organisation',
    sectorLabel: 'Financial',
    teamTerm: 'Operating unit',
    metrics: { teams: 20, packsReady: 6, elevated: 2, privacyGate: '✓' },
    trendPath: TREND.financial,
    teams: [
      { id: 'fn1', name: 'Operations Risk', state: 'Normal', participation: 91, privacyGate: 'Passed', latestAction: 'Controls review complete', packReadiness: 'Ready' },
      { id: 'fn2', name: 'Client Services', state: 'Normal', participation: 87, privacyGate: 'Passed', latestAction: 'Workload review logged', packReadiness: 'Ready' },
      { id: 'fn3', name: 'Controls Team', state: 'Watch', participation: 79, privacyGate: 'Passed', latestAction: 'Escalation review open', packReadiness: 'Draft' },
      { id: 'fn4', name: 'Compliance Team', state: 'Elevated', participation: 74, privacyGate: 'Passed', latestAction: 'Management oversight logged', packReadiness: 'Draft' },
    ],
    packs: [
      { id: 'fnp1', title: 'Operations resilience pack', team: 'Operations Risk', sector: 'Financial', dateRange: 'Apr 1 to Jun 30', readiness: 'Ready' },
      { id: 'fnp2', title: 'Compliance team evidence pack', team: 'Compliance Team', sector: 'Financial', dateRange: 'Jun 1 to Jun 30', readiness: 'Draft' },
      { id: 'fnp3', title: 'Controls team review pack', team: 'Controls Team', sector: 'Financial', dateRange: 'May 1 to Jun 30', readiness: 'Ready' },
    ],
    interventions: [
      { id: 'fni1', title: 'Workload review · Client Services', team: 'Client Services', trigger: 'Watch operating conditions', action: 'Workload rebalance logged', owner: 'Service Manager', status: 'Resolved', outcome: 'Backlog reducing', followUpDate: '2026-06-13', linkedPack: 'Operations resilience pack' },
      { id: 'fni2', title: 'Escalation review · Controls', team: 'Controls Team', trigger: 'Watch threshold passed', action: 'Escalation pathway review', owner: 'Controls Lead', status: 'Active', outcome: 'Under review', followUpDate: '2026-06-10' },
      { id: 'fni3', title: 'Oversight action · Compliance Team', team: 'Compliance Team', trigger: 'Elevated operating conditions', action: 'Management oversight recorded', owner: 'Organisation Admin', status: 'Active', outcome: 'Action in progress', followUpDate: '2026-06-08', linkedPack: 'Compliance team evidence pack' },
    ],
    auditEvents: [
      { id: 'fna1', type: 'Privacy gate passed', timestamp: '2026-06-06 10:05', actor: 'Organisation Admin', detail: 'Operations Risk threshold validated.' },
      { id: 'fna2', type: 'Operating condition changed', timestamp: '2026-06-05 17:30', actor: 'Controls Lead', detail: 'Compliance Team moved to Elevated.' },
      { id: 'fna3', type: 'Management action logged', timestamp: '2026-06-05 12:15', actor: 'Service Manager', detail: 'Client Services workload review recorded.' },
      { id: 'fna4', type: 'Evidence pack compiled', timestamp: '2026-06-04 15:40', actor: 'Auditor', detail: 'Operations resilience pack compiled.' },
      { id: 'fna5', type: 'Pack reviewed', timestamp: '2026-06-03 09:50', actor: 'Organisation Admin', detail: 'Controls team review pack marked reviewed.' },
    ],
    privacyLog: [
      { id: 'fnpl1', team: 'Operations Risk', check: 'Team size threshold', teamSize: 15, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Team totals only. No individual data stored.' },
      { id: 'fnpl2', team: 'Client Services', check: 'Privacy gate', teamSize: 18, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Threshold passed. Reporting enabled.' },
      { id: 'fnpl3', team: 'Desk Micro Unit', check: 'Suppressed period', teamSize: 6, threshold: 10, badge: 'Suppressed', period: 'Week 22', message: 'Below minimum team size. Aggregates withheld.' },
      { id: 'fnpl4', team: 'Closed Desk', check: 'Retention purge', teamSize: 10, threshold: 10, badge: 'Purged', period: 'Week 16', message: 'Expired records purged per retention policy.' },
    ],
    policy: {
      minTeamThreshold: 10,
      reviewPeriodWeeks: 4,
      evidenceRetentionMonths: 24,
      watchThreshold: 2.6,
      elevatedThreshold: 3.6,
      sectorLabel: 'Operating resilience',
      complianceLabel: 'FCA-ready evidence',
    },
  },
  legal: {
    organisation: 'Legal Organisation',
    sectorLabel: 'Legal',
    teamTerm: 'Practice team',
    metrics: { teams: 16, packsReady: 5, elevated: 2, privacyGate: '✓' },
    trendPath: TREND.legal,
    teams: [
      { id: 'l1', name: 'Casework Team', state: 'Normal', participation: 90, privacyGate: 'Passed', latestAction: 'Workload review complete', packReadiness: 'Ready' },
      { id: 'l2', name: 'Fee-earner Team', state: 'Watch', participation: 81, privacyGate: 'Passed', latestAction: 'Capacity review open', packReadiness: 'Draft' },
      { id: 'l3', name: 'Compliance Team', state: 'Normal', participation: 88, privacyGate: 'Passed', latestAction: 'Governance review logged', packReadiness: 'Ready' },
      { id: 'l4', name: 'Client Intake Team', state: 'Elevated', participation: 75, privacyGate: 'Passed', latestAction: 'Escalation review active', packReadiness: 'Draft' },
    ],
    packs: [
      { id: 'lp1', title: 'Casework governance pack', team: 'Casework Team', sector: 'Legal', dateRange: 'Apr 1 to Jun 30', readiness: 'Ready' },
      { id: 'lp2', title: 'Fee-earner workload pack', team: 'Fee-earner Team', sector: 'Legal', dateRange: 'Jun 1 to Jun 30', readiness: 'Draft' },
      { id: 'lp3', title: 'Compliance review pack', team: 'Compliance Team', sector: 'Legal', dateRange: 'May 1 to Jun 30', readiness: 'Ready' },
    ],
    interventions: [
      { id: 'li1', title: 'Workload review · Casework', team: 'Casework Team', trigger: 'Watch operating conditions', action: 'Workload review logged', owner: 'Practice Manager', status: 'Resolved', outcome: 'Backlog reducing', followUpDate: '2026-06-12', linkedPack: 'Casework governance pack' },
      { id: 'li2', title: 'Capacity review · Fee-earner', team: 'Fee-earner Team', trigger: 'Watch threshold passed', action: 'Capacity review opened', owner: 'Compliance Lead', status: 'Active', outcome: 'Under review', followUpDate: '2026-06-10' },
      { id: 'li3', title: 'Escalation review · Client Intake', team: 'Client Intake Team', trigger: 'Elevated operating conditions', action: 'Escalation review recorded', owner: 'Organisation Admin', status: 'Active', outcome: 'Action in progress', followUpDate: '2026-06-08', linkedPack: 'Fee-earner workload pack' },
    ],
    auditEvents: [
      { id: 'la1', type: 'Privacy gate passed', timestamp: '2026-06-06 09:45', actor: 'Organisation Admin', detail: 'Casework Team threshold validated.' },
      { id: 'la2', type: 'Operating condition changed', timestamp: '2026-06-05 16:10', actor: 'Practice Manager', detail: 'Client Intake Team moved to Elevated.' },
      { id: 'la3', type: 'Management action logged', timestamp: '2026-06-05 11:30', actor: 'Compliance Lead', detail: 'Fee-earner capacity review recorded.' },
      { id: 'la4', type: 'Evidence pack compiled', timestamp: '2026-06-04 14:25', actor: 'Auditor', detail: 'Casework governance pack compiled.' },
      { id: 'la5', type: 'Pack reviewed', timestamp: '2026-06-03 10:15', actor: 'Organisation Admin', detail: 'Compliance review pack marked reviewed.' },
    ],
    privacyLog: [
      { id: 'lpl1', team: 'Casework Team', check: 'Team size threshold', teamSize: 12, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Team totals only. No individual data stored.' },
      { id: 'lpl2', team: 'Fee-earner Team', check: 'Privacy gate', teamSize: 14, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Threshold passed. Reporting enabled.' },
      { id: 'lpl3', team: 'Micro Practice Cell', check: 'Suppressed period', teamSize: 7, threshold: 10, badge: 'Suppressed', period: 'Week 22', message: 'Below minimum team size. Aggregates withheld.' },
      { id: 'lpl4', team: 'Archive Matter Team', check: 'Retention purge', teamSize: 11, threshold: 10, badge: 'Purged', period: 'Week 17', message: 'Expired records purged per retention policy.' },
    ],
    policy: {
      minTeamThreshold: 10,
      reviewPeriodWeeks: 4,
      evidenceRetentionMonths: 24,
      watchThreshold: 2.5,
      elevatedThreshold: 3.5,
      sectorLabel: 'Practice team',
      complianceLabel: 'SRA-ready evidence',
    },
  },
  education: {
    organisation: 'Education Organisation',
    sectorLabel: 'Education',
    teamTerm: 'Teaching team',
    metrics: { teams: 22, packsReady: 6, elevated: 2, privacyGate: '✓' },
    trendPath: TREND.education,
    teams: [
      { id: 'e1', name: 'Year Seven Team', state: 'Normal', participation: 91, privacyGate: 'Passed', latestAction: 'Leadership review complete', packReadiness: 'Ready' },
      { id: 'e2', name: 'Learning Support', state: 'Watch', participation: 80, privacyGate: 'Passed', latestAction: 'Support review open', packReadiness: 'Draft' },
      { id: 'e3', name: 'Safeguarding', state: 'Normal', participation: 87, privacyGate: 'Passed', latestAction: 'Routine review logged', packReadiness: 'Ready' },
      { id: 'e4', name: 'Teaching Team B', state: 'Elevated', participation: 74, privacyGate: 'Passed', latestAction: 'Workload review active', packReadiness: 'Draft' },
    ],
    packs: [
      { id: 'ep1', title: 'Year Seven leadership pack', team: 'Year Seven Team', sector: 'Education', dateRange: 'Apr 1 to Jun 30', readiness: 'Ready' },
      { id: 'ep2', title: 'Learning support evidence pack', team: 'Learning Support', sector: 'Education', dateRange: 'Jun 1 to Jun 30', readiness: 'Draft' },
      { id: 'ep3', title: 'Safeguarding review pack', team: 'Safeguarding', sector: 'Education', dateRange: 'May 1 to Jun 30', readiness: 'Ready' },
    ],
    interventions: [
      { id: 'ei1', title: 'Leadership review · Year Seven', team: 'Year Seven Team', trigger: 'Watch operating conditions', action: 'Leadership review logged', owner: 'Head of Year', status: 'Resolved', outcome: 'Pressure reducing', followUpDate: '2026-06-13', linkedPack: 'Year Seven leadership pack' },
      { id: 'ei2', title: 'Support review · Learning Support', team: 'Learning Support', trigger: 'Watch threshold passed', action: 'Support review opened', owner: 'Safeguarding Lead', status: 'Active', outcome: 'Under review', followUpDate: '2026-06-11' },
      { id: 'ei3', title: 'Workload review · Teaching Team B', team: 'Teaching Team B', trigger: 'Elevated operating conditions', action: 'Workload review recorded', owner: 'Organisation Admin', status: 'Active', outcome: 'Action in progress', followUpDate: '2026-06-09', linkedPack: 'Learning support evidence pack' },
    ],
    auditEvents: [
      { id: 'ea1', type: 'Privacy gate passed', timestamp: '2026-06-06 08:35', actor: 'Organisation Admin', detail: 'Year Seven Team threshold validated.' },
      { id: 'ea2', type: 'Operating condition changed', timestamp: '2026-06-05 15:50', actor: 'Head of Year', detail: 'Teaching Team B moved to Elevated.' },
      { id: 'ea3', type: 'Management action logged', timestamp: '2026-06-05 10:40', actor: 'Safeguarding Lead', detail: 'Learning Support review recorded.' },
      { id: 'ea4', type: 'Evidence pack compiled', timestamp: '2026-06-04 13:50', actor: 'Auditor', detail: 'Year Seven leadership pack compiled.' },
      { id: 'ea5', type: 'Pack reviewed', timestamp: '2026-06-03 09:20', actor: 'Organisation Admin', detail: 'Safeguarding review pack marked reviewed.' },
    ],
    privacyLog: [
      { id: 'epl1', team: 'Year Seven Team', check: 'Team size threshold', teamSize: 15, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Team totals only. No individual data stored.' },
      { id: 'epl2', team: 'Learning Support', check: 'Privacy gate', teamSize: 11, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Threshold passed. Reporting enabled.' },
      { id: 'epl3', team: 'Tutor Group C', check: 'Suppressed period', teamSize: 8, threshold: 10, badge: 'Suppressed', period: 'Week 22', message: 'Below minimum team size. Aggregates withheld.' },
      { id: 'epl4', team: 'Archive Cohort', check: 'Retention purge', teamSize: 12, threshold: 10, badge: 'Purged', period: 'Week 16', message: 'Expired records purged per retention policy.' },
    ],
    policy: {
      minTeamThreshold: 10,
      reviewPeriodWeeks: 4,
      evidenceRetentionMonths: 24,
      watchThreshold: 2.4,
      elevatedThreshold: 3.4,
      sectorLabel: 'Teaching team',
      complianceLabel: 'Leadership-ready evidence',
    },
  },
  corporate: {
    organisation: 'Corporate Governance Team',
    sectorLabel: 'Corporate',
    teamTerm: 'Department',
    metrics: { teams: 18, packsReady: 6, elevated: 2, privacyGate: 'Pass' },
    trendPath: TREND.corporate,
    teams: [
      { id: 'c1', name: 'Operations', state: 'Normal', participation: 93, privacyGate: 'Passed', latestAction: 'Capacity review complete', packReadiness: 'Ready' },
      { id: 'c2', name: 'Customer Support', state: 'Elevated', participation: 77, privacyGate: 'Passed', latestAction: 'Workload review active', packReadiness: 'Ready' },
      { id: 'c3', name: 'Compliance', state: 'Watch', participation: 84, privacyGate: 'Passed', latestAction: 'Governance review open', packReadiness: 'Draft' },
      { id: 'c4', name: 'People Ops', state: 'Normal', participation: 89, privacyGate: 'Passed', latestAction: 'Routine review logged', packReadiness: 'Ready' },
      { id: 'c5', name: 'Finance Team', state: 'Normal', participation: 91, privacyGate: 'Passed', latestAction: 'Quarterly review complete', packReadiness: 'Ready' },
    ],
    packs: [
      { id: 'cp1', title: 'Customer Support evidence pack', team: 'Customer Support', sector: 'Corporate', dateRange: 'Apr 1 to Jun 30', readiness: 'Ready' },
      { id: 'cp2', title: 'Compliance governance pack', team: 'Compliance', sector: 'Corporate', dateRange: 'Jun 1 to Jun 30', readiness: 'Draft' },
      { id: 'cp3', title: 'Operations resilience pack', team: 'Operations', sector: 'Corporate', dateRange: 'May 1 to Jun 30', readiness: 'Ready' },
    ],
    interventions: [
      { id: 'ci1', title: 'Workload review · Customer Support', team: 'Customer Support', trigger: 'Elevated operating conditions', action: 'Workload review logged', owner: 'Department Lead', status: 'Active', outcome: 'Follow-up scheduled', followUpDate: '2026-06-14', linkedPack: 'Customer Support evidence pack' },
      { id: 'ci2', title: 'Governance review · Compliance', team: 'Compliance', trigger: 'Watch threshold passed', action: 'Governance review opened', owner: 'Governance Manager', status: 'Active', outcome: 'Under review', followUpDate: '2026-06-11' },
      { id: 'ci3', title: 'Capacity review · Operations', team: 'Operations', trigger: 'Watch operating conditions', action: 'Capacity review recorded', owner: 'Operations Director', status: 'Resolved', outcome: 'Capacity stabilised', followUpDate: '2026-06-09', linkedPack: 'Operations resilience pack' },
    ],
    auditEvents: [
      { id: 'ca1', type: 'Privacy gate passed', timestamp: '2026-06-06 09:30', actor: 'Organisation Admin', detail: 'Customer Support threshold validated for reporting window.' },
      { id: 'ca2', type: 'Operating condition changed', timestamp: '2026-06-05 14:20', actor: 'Department Lead', detail: 'Customer Support moved to Elevated.' },
      { id: 'ca3', type: 'Management action logged', timestamp: '2026-06-05 10:05', actor: 'Governance Manager', detail: 'Compliance governance review recorded.' },
      { id: 'ca4', type: 'Evidence pack compiled', timestamp: '2026-06-04 13:15', actor: 'Auditor', detail: 'Customer Support evidence pack marked ready.' },
      { id: 'ca5', type: 'Management action logged', timestamp: '2026-06-03 11:40', actor: 'Operations Director', detail: 'Operations capacity review recorded.' },
    ],
    privacyLog: [
      { id: 'cpl1', team: 'Operations', check: 'Team size threshold', teamSize: 16, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Team totals only. No individual data stored.' },
      { id: 'cpl2', team: 'Customer Support', check: 'Privacy gate', teamSize: 14, threshold: 10, badge: 'Passed', period: 'Week 23', message: 'Threshold passed. Reporting enabled.' },
      { id: 'cpl3', team: 'Project Cell A', check: 'Suppressed period', teamSize: 7, threshold: 10, badge: 'Suppressed', period: 'Week 22', message: 'Below minimum team size. Aggregates withheld.' },
      { id: 'cpl4', team: 'Legacy Support Unit', check: 'Retention purge', teamSize: 11, threshold: 10, badge: 'Purged', period: 'Week 18', message: 'Expired records purged per retention policy.' },
    ],
    policy: {
      minTeamThreshold: 10,
      reviewPeriodWeeks: 4,
      evidenceRetentionMonths: 24,
      watchThreshold: 2.5,
      elevatedThreshold: 3.5,
      sectorLabel: 'Corporate department',
      complianceLabel: 'Internal governance evidence',
    },
  },
};

export function cloneSectorData(): Record<SectorKey, SectorData> {
  return structuredClone(INITIAL_SECTOR_DATA);
}
